baseURL = 'https://DavHau.com'
languageCode = 'en-us'
title = 'DavHau - David Hauer'

# wrapped hugo hardcodes the theme from the flake input `hugo-theme` as `theme`
theme = "theme"
# uglyurls = true
# relativeURLs = true

[markup]
  [markup.highlight]
    style = 'monokai'

[params]
  author = "David Hauer"
  info = """
    Reproducible Infrastructure and Packaging
    Nix & NixOS Magician
  """
  description = "David Hauer's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://numtide.com/content/images/size/w600/2023/03/oceansprint-2022-2-cropped.jpg"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 1993

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/DavHau/"

# Menu links
#[[menu.main]]
#  name = "Blog"
#  weight = 1
#  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 1
  url  = "projects/"
